version: "2"
services:
  nginx:
    image: nginx
    volumes:
      - ./site.conf:/etc/nginx/conf.d/default.conf
      - ./code:/code
    ports:
      - "80:80"
  php:
    image: php:fpm
    volumes:
      - ./code:/code
