version: "2"
services:
  nginx:
    image: nginx
    volumes:
      - ./code:/code
      - ./site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./code:/code
  mysql:
    image: mysql
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_DATABASE: "test"
      MYSQL_ROOT_PASSWORD: "mypass"
