version: "2"
services:
  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./my-site.conf:/etc/nginx/conf.d/default.conf
      - ./code:/code
  php:
    image: php:fpm
    volumes:
      - ./code:/code
