version: "2"
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./code:/code
      - ./mysite.conf:/etc/nginx/conf.d/default.conf
  php:
    image: php:fpm
    volumes:
      - ./code:/code
